"""add_dts_tables

Revision ID: 91d3e8135c84
Revises: dd33dfdbc598
Create Date: 2026-07-22 20:16:25.378664
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '91d3e8135c84'
down_revision: Union[str, None] = 'dd33dfdbc598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('db_host', sa.String(length=200), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=200), nullable=False),
    sa.Column('db_username', sa.String(length=200), nullable=False),
    sa.Column('db_password', sa.String(length=500), nullable=False),
    sa.Column('extract_mode', sa.String(length=20), nullable=False),
    sa.Column('extract_sql', sa.Text(), nullable=True),
    sa.Column('extract_table', sa.String(length=200), nullable=True),
    sa.Column('incremental_column', sa.String(length=100), nullable=True),
    sa.Column('incremental_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('db_host', sa.String(length=200), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=200), nullable=False),
    sa.Column('db_username', sa.String(length=200), nullable=False),
    sa.Column('db_password', sa.String(length=500), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('write_mode', sa.String(length=30), nullable=False),
    sa.Column('upsert_keys', sa.JSON(), nullable=False),
    sa.Column('auto_create_table', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('etl_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('target_table_id', sa.String(length=36), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('error_retry_count', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['target_table_id'], ['target_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_job_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etl_job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_rows', sa.Integer(), nullable=True),
    sa.Column('output_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('executed_sql', sa.Text(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etl_job_id'], ['etl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_job_runs')
    op.drop_table('etl_jobs')
    op.drop_table('target_tables')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
