"""initial_schema

Revision ID: dd33dfdbc598
Revises: 
Create Date: 2026-07-22 16:22:12.718593
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dd33dfdbc598'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('executed_sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('output_file', sa.String(length=500), nullable=True),
    sa.Column('input_rows', sa.Integer(), nullable=True),
    sa.Column('output_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookup_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=200), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('lookup_table_id', sa.String(length=36), nullable=True),
    sa.Column('depends_on', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_field_name'), 'rules', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_field_name'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('lookup_tables')
    op.drop_table('execution_tasks')
    # ### end Alembic commands ###
